train:
  _target_: src.datasets.LJSpeechChunkDataset
  audio_len: 8192  # cropped audio length
  sample_rate: 22050
  limit: 10

val:
  _target_: src.datasets.LJSpeechDataset
  limit: 5

test:
  _target_: src.datasets.YandexDownloadDataset
  limit: 1
