train: # metrics that are calculated during training
  - _target_: src.metrics.MOS
    device: ${trainer.device}
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.MOS
    device: ${trainer.device}
