defaults:
  - model: hifi_gan_v2
  - writer: wandb
  - metrics: train_inference_mos
  - datasets: LJSpeech_YaTest
  - dataloader: colab
  - transforms: only_batch
  - _self_
optimizer_d:
  _target_: torch.optim.AdamW
  lr: 2e-5
  betas: [0.8, 0.99]
  weight_decay: 0.01
optimizer_g:
  _target_: torch.optim.AdamW
  lr: 2e-5
  betas: [0.8, 0.99]
  weight_decay: 0.01
lr_scheduler_d:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  eta_min: 1e-6
  T_max: 500 # n_epochs * epoch_len
lr_scheduler_g:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  eta_min: 1e-6
  T_max: 500 # n_epochs * epoch_len
loss_function_d:
  _target_: src.loss.DiscriminatorLoss
loss_function_g:
  _target_: src.loss.GeneratorLoss
trainer:
  log_step: 10
  n_epochs: 50
  epoch_len: 10 # 13100 / 64(batch_size) â‰ˆ 200 steps
  device_tensors: ["audio", "mel_spectrogram"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  monitor: "max MOS" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 10 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  parallel: False
  save_reproducibility: False
  dtype: "float32"
  seed: 1
