defaults:
  - model: hifi_gan_v2
  - metrics: inference_mos
  - datasets: CustomInference # we do not want to run inference on training data
  - dataloader: colab
  - transforms: only_batch
  - _self_
inferencer:
  device_tensors: ["audio", "mel_spectrogram"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: ${inferencer.dataset_name} # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/model_best.pth" # path to the pretrained model
  dataset_name: "test_data"
  texts_query: ""
  use_text2mel: False
