defaults:
  - _self_

# these lines are required if you do not use batch transforms
batch_transforms:
  train: null
  inference: null

# these lines are required if you do not use instance transforms
instance_transforms:
  train: null
  inference: null
